// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function AppRun(arg1:string,arg2:string):Promise<main.Result>;

export function Greet(arg1:string):Promise<string>;

export function LoadOptions():Promise<Array<string>>;

export function QueryMovie(arg1:string):Promise<Array<model.QueryResult>>;

export function WriteConfig(arg1:string,arg2:string,arg3:string):Promise<string>;
